version: '3.7'

services:
  db1:
    image: postgres
    container_name: db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - ./db1:/var/lib/postgresql/data
    networks:
      - personal

  db2:
    image: postgres
    container_name: db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - ./db2:/var/lib/postgresql/data
    networks:
      - personal

networks:
  personal:
    driver: bridge